import { useState, useEffect, useMemo } from "react";
import { useDispatch, useSelector } from "react-redux";
import type { RootState, AppDispatch } from "../../services/store/store";
import { useProviderContext } from "../../context/useProviderContext";
import { fetchAuthorizations } from "../../services/thunks/authorizationThunk";
import { formatDate, dateFormats } from "../../utils/dateFormatter"; 
import EmptyState from "../../components/ui/EmptyState";
import FormHeader from "../../components/form/FormHeader";
import { FaEye } from "react-icons/fa";

// Import table dependencies
import {
  useReactTable,
  getCoreRowModel,
  getSortedRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  type ColumnDef,
  type SortingState,
  type ColumnFiltersState,
  type VisibilityState,
} from "@tanstack/react-table";
import { flexRender } from "@tanstack/react-table";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../../components/table";
import { Pagination } from "../../components/pagination";
import { LoadingSpinner } from "../../components/ui/LoadingSpinner";
import AuthorizationDetailsModal from "../../components/ui/AuthorizationDetailsModal"; 

export const Authorization = () => {
  const dispatch = useDispatch<AppDispatch>();
  const { selectedProviderId } = useProviderContext();
  const hmoId = useSelector((s: RootState) => s.auth.user?.hmoId);
  
  // Get authorization data from Redux store
  const { data: authorizations, loading, error } = useSelector((s: RootState) => s.authorizations);
  
  // Table states
  const [sorting, setSorting] = useState<SortingState>([]);
  const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);
  const [columnVisibility, setColumnVisibility] = useState<VisibilityState>({});
  const [rowSelection, setRowSelection] = useState({});
  const [pageIndex, setPageIndex] = useState(0);
  const [pageSize, setPageSize] = useState(10);
  const [searchTerm, setSearchTerm] = useState("");

  // Modal states
  const [showDetailsModal, setShowDetailsModal] = useState(false);
  const [selectedAuthorization, setSelectedAuthorization] = useState<any>(null);

  // Load authorizations
  useEffect(() => {
    if (selectedProviderId && hmoId) {
      dispatch(fetchAuthorizations({
        providerId: selectedProviderId,
        hmoId: hmoId,
        // Optional params can be added here
        // startDate: '2024-01-01',
        // endDate: '2024-12-31',
      }));
    }
  }, [dispatch, selectedProviderId, hmoId]);

  // Map authorization data for table
  const mappedAuthorizations = useMemo(() => {
    return authorizations.map((auth, index) => ({
      sn: index + 1,
      requestId: auth.authorizationNumber || auth.id.substring(0, 8), // Use auth number or truncated ID
      date: formatDate(auth.requestDate, dateFormats.short),
      healthProvider: "FMC, Asaba", // need to get this from provider context
      enrolleeId: auth.enrolleeIdNumber,
      enrolleeName: auth.enrolleeName,
      diagnosis: auth.diagnosis,
      generatedBy: auth.requestSource || 'Enrollee',
      approvalBy: 'John Doe', //  from API
      status: auth.authorizationStatus,
      id: auth.id,
      rawData: auth, // Store full authorization data for details
    }));
  }, [authorizations]);

  // Define columns based on your required fields
  const columns: ColumnDef<any>[] = [
    { accessorKey: 'sn', header: 'S/N', size: 60 },
    { accessorKey: 'requestId', header: 'Request ID' },
    { accessorKey: 'date', header: 'Date' },
    { accessorKey: 'healthProvider', header: 'Health Provider' },
    { accessorKey: 'enrolleeId', header: 'Enrollee ID' },
    { accessorKey: 'enrolleeName', header: 'Enrollee Name' },
    { accessorKey: 'diagnosis', header: 'Diagnosis' },
    { accessorKey: 'generatedBy', header: 'Generated By' },
    { accessorKey: 'approvalBy', header: 'Approval By' },
    {
      accessorKey: 'status',
      header: 'Status',
      cell: ({ row }) => {
        const status = row.original.status;
        const statusColor = {
          Pending: "#f59e0b", // amber
          Approved: "#217346", // green
          Rejected: "#d32f2f", // red
          Completed: "#6b6f80", // gray
        };
        return (
          <span
            style={{
              color: statusColor[status as keyof typeof statusColor] || "#6b6f80",
              fontWeight: 600,
            }}
          >
            {status}
          </span>
        );
      },
    },
    {
      id: 'action',
      enableHiding: false,
      cell: ({ row }) => {
        return (
          <button
            className="cursor-pointer text-green-600 hover:text-green-800 transition-colors"
            title="View Details"
            onClick={() => handleViewAuthorization(row.original.rawData)}
          >
            <FaEye size={16} />
          </button>
        );
      },
    },
  ];

  // Initialize table
  const table = useReactTable({
    data: mappedAuthorizations,
    columns,
    state: {
      sorting,
      columnVisibility,
      rowSelection,
      columnFilters,
      pagination: { pageIndex, pageSize },
    },
    onSortingChange: setSorting,
    onColumnVisibilityChange: setColumnVisibility,
    onRowSelectionChange: setRowSelection,
    onColumnFiltersChange: setColumnFilters,
    onPaginationChange: updater => {
      if (typeof updater === 'function') {
        const newState = updater(table.getState().pagination);
        setPageIndex(newState.pageIndex);
        setPageSize(newState.pageSize);
      } else {
        setPageIndex(updater.pageIndex);
        setPageSize(updater.pageSize);
      }
    },
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
  });

  const totalPages = table.getPageCount();

  // Handle view authorization details
  const handleViewAuthorization = (authorization: any) => {
    setSelectedAuthorization(authorization);
    setShowDetailsModal(true);
  };

  return (
    <>
  
    <div className="p-6">
      <div className="bg-gray-100 overflow-scroll h-full">
        <div className="bg-white rounded-md flex flex-col mb-36">
          {/* Header */}
          <div className="flex flex-wrap gap-4 justify-between items-center p-6">
            <div className="flex items-center gap-8">
              <FormHeader>Authorization Requests</FormHeader>
              <input
                type="text"
                placeholder="Search authorizations"
                value={searchTerm}
                onChange={e => {
                  setSearchTerm(e.target.value);
                  table.setGlobalFilter(e.target.value);
                }}
                className="border rounded-lg hidden lg:block px-4 py-2 lg:w-96 lg:max-w-2xl focus:outline-none focus:ring-2 focus:ring-green-500"
              />
            </div>
          </div>

          <div>
            {loading ? (
              <div className="flex items-center justify-center h-64">
                <LoadingSpinner />
              </div>
            ) : error ? (
              <div className="text-red-500 text-center py-10">
                Failed to load authorizations: {error}
              </div>
            ) : authorizations.length === 0 ? (
              <EmptyState
                icon={<span>📋</span>}
                title="No authorization requests available"
                description="Authorization requests will appear here once submitted."
              />
            ) : (
              <>
                {/* Table */}
                <div className="flex-1 lg:px-0 lg:mt-4 overflow-x-auto">
                  <Table className="min-w-[1000px]">
                    <TableHeader className="border-y border-[#CDE5F9] bg-gray-50">
                      {table.getHeaderGroups().map(headerGroup => (
                        <TableRow key={headerGroup.id}>
                          {headerGroup.headers.map(header => (
                            <TableHead key={header.id} className="font-semibold text-gray-700">
                              {header.isPlaceholder
                                ? null
                                : flexRender(
                                    header.column.columnDef.header,
                                    header.getContext(),
                                  )}
                            </TableHead>
                          ))}
                        </TableRow>
                      ))}
                    </TableHeader>
                    <TableBody>
                      {table.getRowModel().rows.length ? (
                        table.getRowModel().rows.map(row => (
                          <TableRow key={row.id} className="hover:bg-gray-50 transition-colors">
                            {row.getVisibleCells().map(cell => (
                              <TableCell key={cell.id} className="py-3">
                                {flexRender(
                                  cell.column.columnDef.cell,
                                  cell.getContext(),
                                )}
                              </TableCell>
                            ))}
                          </TableRow>
                        ))
                      ) : (
                        <TableRow>
                          <TableCell
                            colSpan={columns.length}
                            className="h-24 text-center"
                          >
                            <div className="flex flex-col items-center gap-4">
                              <span className="font-medium">
                                No authorizations found
                              </span>
                              <span className="font-medium text-gray-600">
                                Try adjusting your search criteria
                              </span>
                            </div>
                          </TableCell>
                        </TableRow>
                      )}
                    </TableBody>
                  </Table>
                </div>

                {/* Pagination */}
                <div className="p-4 flex items-center justify-end border-t">
                  <Pagination
                    totalEntriesSize={table.getFilteredRowModel().rows.length}
                    currentPage={pageIndex + 1}
                    totalPages={totalPages}
                    pageSize={pageSize}
                    onPageChange={p => setPageIndex(p - 1)}
                    onPageSizeChange={size => {
                      setPageSize(size);
                      setPageIndex(0);
                    }}
                  />
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Authorization Details Modal */}
      {showDetailsModal && (
        <AuthorizationDetailsModal
          open={showDetailsModal}
          onClose={() => {
            setShowDetailsModal(false);
            setSelectedAuthorization(null);
          }}
          authorization={selectedAuthorization}
        />
      )}
    </div>
      </>
  );
};